// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landsafe-bright/Civictrust.tsx": () => import("../components/mockups/landsafe-bright/Civictrust.tsx"),
  "./components/mockups/landsafe-bright/Cleanops.tsx": () => import("../components/mockups/landsafe-bright/Cleanops.tsx"),
  "./components/mockups/landsafe-bright/Tactile.tsx": () => import("../components/mockups/landsafe-bright/Tactile.tsx")
};
